# Generated by Django 3.2.3 on 2021-05-19 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleOrdenPedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_individual', models.IntegerField()),
                ('precio_total', models.IntegerField()),
            ],
            options={
                'db_table': 'detalle_orden_pedido',
            },
        ),
        migrations.CreateModel(
            name='OrdenPedido',
            fields=[
                ('id_orden_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('suma_precio', models.IntegerField()),
                ('fecha_recepcion', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orden_pedido',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('rut_proveedor', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=50)),
                ('rubro', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'proveedor',
            },
        ),
        migrations.CreateModel(
            name='ServiciosComedor',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_servicio', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'servicios_comedor',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.IntegerField(primary_key=True, serialize=False)),
                ('familia_producto', models.IntegerField()),
                ('fecha_vencimiento', models.IntegerField()),
                ('tipo_producto', models.IntegerField()),
                ('descripcion_producto', models.CharField(max_length=50)),
                ('precio_producto', models.IntegerField()),
                ('stock_producto', models.IntegerField()),
                ('stock_critico_producto', models.IntegerField()),
                ('rut_proveedor', models.ForeignKey(db_column='rut_proveedor', on_delete=django.db.models.deletion.CASCADE, to='Servicios.proveedor')),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='Platos',
            fields=[
                ('id_plato', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_plato', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio_plato', models.IntegerField()),
                ('id_servicio', models.ForeignKey(db_column='id_servicio', on_delete=django.db.models.deletion.CASCADE, to='Servicios.servicioscomedor')),
            ],
            options={
                'db_table': 'platos',
            },
        ),
    ]
