# Generated by Django 3.2.3 on 2021-05-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0003_alter_producto_id_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenpedido',
            name='fecha_recepcion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
