# Generated by Django 3.2.3 on 2021-05-19 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
    ]
