# Generated by Django 3.2.3 on 2021-05-19 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('nro_factura', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.IntegerField()),
                ('estado_factura', models.BooleanField()),
            ],
            options={
                'db_table': 'factura',
            },
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('nro_habitacion', models.IntegerField(primary_key=True, serialize=False)),
                ('estado_habitacion', models.BooleanField()),
                ('tipo_cama', models.CharField(max_length=40)),
                ('accesorios_habitacion', models.CharField(max_length=50)),
                ('precio_habitacion', models.IntegerField()),
            ],
            options={
                'db_table': 'habitacion',
            },
        ),
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('id_huesped', models.AutoField(primary_key=True, serialize=False)),
                ('rut_huesped', models.CharField(max_length=10)),
                ('nombre_huesped', models.CharField(max_length=60)),
                ('fecha_recepcion', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'huesped',
            },
        ),
        migrations.CreateModel(
            name='OrdenDeCompra',
            fields=[
                ('id_orden_compra', models.AutoField(primary_key=True, serialize=False)),
                ('servicios_contratados', models.CharField(max_length=50)),
                ('cantidad_huespedes', models.IntegerField()),
                ('fecha_orden_compra', models.DateField()),
                ('tipos_habitacion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'orden_de_compra',
            },
        ),
    ]
